package com.calf.demo.renouvellementdecontrat.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Qualification de la nouvelle délégation")
public class CritereDelegation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Eligibilité Ajout")
	private java.lang.Boolean eligibiliteAjout;
	@org.kie.api.definition.type.Label(value = "Eligibilité Dérogation")
	private java.lang.Boolean eligibiliteDerogation;
	@org.kie.api.definition.type.Label(value = "Risque Ajout")
	private java.lang.Boolean risqueAjout;
	@org.kie.api.definition.type.Label(value = "Risque Dérogation")
	private java.lang.Boolean risqueDerogation;

	public CritereDelegation() {
	}

	public java.lang.Boolean getEligibiliteAjout() {
		return this.eligibiliteAjout;
	}

	public void setEligibiliteAjout(java.lang.Boolean eligibiliteAjout) {
		this.eligibiliteAjout = eligibiliteAjout;
	}

	public java.lang.Boolean getEligibiliteDerogation() {
		return this.eligibiliteDerogation;
	}

	public void setEligibiliteDerogation(java.lang.Boolean eligibiliteDerogation) {
		this.eligibiliteDerogation = eligibiliteDerogation;
	}

	public java.lang.Boolean getRisqueAjout() {
		return this.risqueAjout;
	}

	public void setRisqueAjout(java.lang.Boolean risqueAjout) {
		this.risqueAjout = risqueAjout;
	}

	public java.lang.Boolean getRisqueDerogation() {
		return this.risqueDerogation;
	}

	public void setRisqueDerogation(java.lang.Boolean risqueDerogation) {
		this.risqueDerogation = risqueDerogation;
	}

	public CritereDelegation(java.lang.Boolean eligibiliteAjout,
			java.lang.Boolean eligibiliteDerogation,
			java.lang.Boolean risqueAjout, java.lang.Boolean risqueDerogation) {
		this.eligibiliteAjout = eligibiliteAjout;
		this.eligibiliteDerogation = eligibiliteDerogation;
		this.risqueAjout = risqueAjout;
		this.risqueDerogation = risqueDerogation;
	}

}