package com.calf.demo.renouvellementdecontrat.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Critères du dossier")
@org.kie.api.definition.type.Description("Représente les critères d'un dossier")
public class CritereDossier implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Compte de garantie")
	private java.lang.String compteGarantie;
	@org.kie.api.definition.type.Label("Cotation ANADEFI")
	private java.lang.String cotation;

	@org.kie.api.definition.type.Label("Engagement global")
	private java.lang.Integer montantEngagement;

	@org.kie.api.definition.type.Label("Sans Assurance")
	private java.lang.Boolean sansAssurance;

	@org.kie.api.definition.type.Label("Type de produit")
	private java.lang.String typeProduit;

	public CritereDossier() {
	}

	public java.lang.String getCompteGarantie() {
		return this.compteGarantie;
	}

	public void setCompteGarantie(java.lang.String compteGarantie) {
		this.compteGarantie = compteGarantie;
	}

	public java.lang.String getCotation() {
		return this.cotation;
	}

	public void setCotation(java.lang.String cotation) {
		this.cotation = cotation;
	}

	public java.lang.Integer getMontantEngagement() {
		return this.montantEngagement;
	}

	public void setMontantEngagement(java.lang.Integer montantEngagement) {
		this.montantEngagement = montantEngagement;
	}

	public java.lang.Boolean getSansAssurance() {
		return this.sansAssurance;
	}

	public void setSansAssurance(java.lang.Boolean sansAssurance) {
		this.sansAssurance = sansAssurance;
	}

	public java.lang.String getTypeProduit() {
		return this.typeProduit;
	}

	public void setTypeProduit(java.lang.String typeProduit) {
		this.typeProduit = typeProduit;
	}

	public CritereDossier(java.lang.String compteGarantie,
			java.lang.String cotation, java.lang.Integer montantEngagement,
			java.lang.Boolean sansAssurance, java.lang.String typeProduit) {
		this.compteGarantie = compteGarantie;
		this.cotation = cotation;
		this.montantEngagement = montantEngagement;
		this.sansAssurance = sansAssurance;
		this.typeProduit = typeProduit;
	}

}