package com.calf.demo.renouvellementdecontrat.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Validation de la délégation")
public class ValidationDelegation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type de fiche")
	private java.lang.String typeDeFiche;
	@org.kie.api.definition.type.Label("Veuillez motiver la modification de délégation")
	private java.lang.String motifModificationDelegation;

	@org.kie.api.definition.type.Label(value = "Demande d'avis de")
	private java.util.List<java.lang.String> demandeAvisDe;

	public ValidationDelegation() {
	}

	public java.lang.String getTypeDeFiche() {
		return this.typeDeFiche;
	}

	public void setTypeDeFiche(java.lang.String typeDeFiche) {
		this.typeDeFiche = typeDeFiche;
	}

	public java.lang.String getMotifModificationDelegation() {
		return this.motifModificationDelegation;
	}

	public void setMotifModificationDelegation(
			java.lang.String motifModificationDelegation) {
		this.motifModificationDelegation = motifModificationDelegation;
	}

	public java.util.List<java.lang.String> getDemandeAvisDe() {
		return this.demandeAvisDe;
	}

	public void setDemandeAvisDe(java.util.List<java.lang.String> demandeAvisDe) {
		this.demandeAvisDe = demandeAvisDe;
	}

	public ValidationDelegation(java.lang.String typeDeFiche,
			java.lang.String motifModificationDelegation,
			java.util.List<java.lang.String> demandeAvisDe) {
		this.typeDeFiche = typeDeFiche;
		this.motifModificationDelegation = motifModificationDelegation;
		this.demandeAvisDe = demandeAvisDe;
	}

}